import type {
  MonitoredUser,
  Alert,
  GeofenceZone,
  LocationHistoryPoint,
} from "@/types"

const now = new Date()
const isoNow = now.toISOString()

const geofenceZones: GeofenceZone[] = [
  {
    id: "zone-1",
    name: "Home",
    type: "home",
    center: { lat: -1.9441, lng: 30.0619 },
    radius: 200,
    color: "#22c55e",
    enabled: true,
  },
  {
    id: "zone-2",
    name: "Work",
    type: "work",
    center: { lat: -1.948, lng: 30.075 },
    radius: 300,
    color: "#3b82f6",
    enabled: true,
  },
  {
    id: "zone-3",
    name: "CHUK Hospital",
    type: "hospital",
    center: { lat: -1.941, lng: 30.071 },
    radius: 150,
    color: "#ef4444",
    enabled: true,
  },
]

const generateLocationHistory = (
  baseLat: number,
  baseLng: number,
  hours: number,
): LocationHistoryPoint[] => {
  const points: LocationHistoryPoint[] = []
  const steps = hours * 6
  for (let i = steps; i >= 0; i--) {
    const minutesAgo = i * 10
    const t = new Date(now.getTime() - minutesAgo * 60 * 1000)
    points.push({
      coordinates: {
        lat: baseLat + (Math.random() - 0.5) * 0.005,
        lng: baseLng + (Math.random() - 0.5) * 0.005,
      },
      timestamp: t.toISOString(),
      speed: Math.random() * 3,
    })
  }
  return points
}

export const mockUsers: MonitoredUser[] = [
  {
    id: "user-1",
    profile: {
      id: "user-1",
      name: "Jean Pierre Habimana",
      age: 67,
      emergencyContact: {
        name: "Sarah Habimana",
        phone: "+250 788 345 678",
        relation: "Daughter",
      },
      medicalNotes: "Glaucoma patient, uses medication daily. Requires regular check-ups.",
      accessibilityNotes: "Uses ENKONI cane for primary mobility. Comfortable with familiar routes.",
      preferredAlertMethods: ["in_app", "sms", "call"],
      safeZones: geofenceZones,
    },
    currentLocation: {
      coordinates: { lat: -1.9441, lng: 30.0619 },
      address: "KG 7 Ave, Kacyiru, Kigali, Rwanda",
      timestamp: isoNow,
      speed: 0.8,
      heading: 180,
    },
    locationHistory: generateLocationHistory(-1.9441, 30.0619, 2),
    device: {
      batteryLevel: 78,
      signalStrength: 85,
      lastConnectionTime: isoNow,
      firmwareVersion: "ENKONI-OS v2.4.1",
      connectionStatus: "online",
      sensors: [
        {
          id: "s1",
          type: "obstacle",
          label: "Front Obstacle",
          status: "active",
          value: "1.2m",
          lastReading: isoNow,
        },
        {
          id: "s2",
          type: "gps",
          label: "GPS Module",
          status: "active",
          value: "8 satellites",
          lastReading: isoNow,
        },
        {
          id: "s3",
          type: "motion",
          label: "Motion Detector",
          status: "active",
          value: "Walking",
          lastReading: isoNow,
        },
        {
          id: "s4",
          type: "gyroscope",
          label: "Gyroscope",
          status: "active",
          value: "Stable",
          lastReading: isoNow,
        },
        {
          id: "s5",
          type: "ultrasonic",
          label: "Ultrasonic Array",
          status: "active",
          value: "3.4m range",
          lastReading: isoNow,
        },
      ],
    },
    metrics: {
      totalDistanceToday: 3.2,
      totalDistanceWeek: 18.7,
      obstaclesDetected: 12,
      tripDuration: 45,
      tripFrequency: 3,
      safetyScore: 94,
      incidents: 0,
    },
    lastUpdated: isoNow,
    geofenceZones,
    status: "moving",
  },
  {
    id: "user-2",
    profile: {
      id: "user-2",
      name: "Mukamana Alice",
      age: 72,
      emergencyContact: {
        name: "Hakizimana Jean",
        phone: "+250 788 456 789",
        relation: "Son",
      },
      medicalNotes: "Diabetic retinopathy, partially sighted. Uses insulin pump.",
      accessibilityNotes: "Prefers morning walks. Has difficulty with uneven terrain.",
      preferredAlertMethods: ["in_app", "sms"],
      safeZones: [
        {
          id: "zone-4",
          name: "Home",
          type: "home",
          center: { lat: -1.951, lng: 30.118 },
          radius: 200,
          color: "#22c55e",
          enabled: true,
        },
      ],
    },
    currentLocation: {
      coordinates: { lat: -1.951, lng: 30.118 },
      address: "KG 15 Ave, Kimironko, Kigali, Rwanda",
      timestamp: new Date(now.getTime() - 2 * 60 * 1000).toISOString(),
      speed: 0,
      heading: 0,
    },
    locationHistory: generateLocationHistory(-1.951, 30.118, 1),
    device: {
      batteryLevel: 34,
      signalStrength: 62,
      lastConnectionTime: new Date(now.getTime() - 2 * 60 * 1000).toISOString(),
      firmwareVersion: "ENKONI-OS v2.3.8",
      connectionStatus: "online",
      sensors: [
        {
          id: "s6",
          type: "obstacle",
          label: "Front Obstacle",
          status: "active",
          value: "Clear",
          lastReading: new Date(now.getTime() - 2 * 60 * 1000).toISOString(),
        },
        {
          id: "s7",
          type: "gps",
          label: "GPS Module",
          status: "active",
          value: "6 satellites",
          lastReading: new Date(now.getTime() - 2 * 60 * 1000).toISOString(),
        },
        {
          id: "s8",
          type: "motion",
          label: "Motion Detector",
          status: "inactive",
          value: "Stationary",
          lastReading: new Date(now.getTime() - 2 * 60 * 1000).toISOString(),
        },
        {
          id: "s9",
          type: "gyroscope",
          label: "Gyroscope",
          status: "active",
          value: "Stable",
          lastReading: new Date(now.getTime() - 2 * 60 * 1000).toISOString(),
        },
        {
          id: "s10",
          type: "ultrasonic",
          label: "Ultrasonic Array",
          status: "active",
          value: "2.1m range",
          lastReading: new Date(now.getTime() - 2 * 60 * 1000).toISOString(),
        },
      ],
    },
    metrics: {
      totalDistanceToday: 1.5,
      totalDistanceWeek: 10.2,
      obstaclesDetected: 5,
      tripDuration: 20,
      tripFrequency: 1,
      safetyScore: 88,
      incidents: 0,
    },
    lastUpdated: new Date(now.getTime() - 2 * 60 * 1000).toISOString(),
    geofenceZones: [
        {
          id: "zone-4",
          name: "Home",
          type: "home",
          center: { lat: -1.951, lng: 30.118 },
          radius: 200,
          color: "#22c55e",
          enabled: true,
        },
      ],
    status: "stationary",
  },
  {
    id: "user-3",
    profile: {
      id: "user-3",
      name: "Bizimana Emmanuel",
      age: 58,
      emergencyContact: {
        name: "Bizimana Marie",
        phone: "+250 788 567 890",
        relation: "Wife",
      },
      medicalNotes: "Macular degeneration. No light perception in left eye.",
      accessibilityNotes: "Requires audio navigation assistance. Familiar with public transport routes.",
      preferredAlertMethods: ["in_app", "sms", "email"],
      safeZones: [
        {
          id: "zone-5",
          name: "Home",
          type: "home",
          center: { lat: -1.97, lng: 30.0528 },
          radius: 200,
          color: "#22c55e",
          enabled: true,
        },
        {
          id: "zone-6",
          name: "Work",
          type: "work",
          center: { lat: -1.958, lng: 30.088 },
          radius: 300,
          color: "#3b82f6",
          enabled: true,
        },
      ],
    },
    currentLocation: {
      coordinates: { lat: -1.958, lng: 30.088 },
      address: "KG 220 St, Remera, Kigali, Rwanda",
      timestamp: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
      speed: 1.2,
      heading: 45,
    },
    locationHistory: generateLocationHistory(-1.958, 30.088, 3),
    device: {
      batteryLevel: 92,
      signalStrength: 91,
      lastConnectionTime: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
      firmwareVersion: "ENKONI-OS v2.4.1",
      connectionStatus: "online",
      sensors: [
        {
          id: "s11",
          type: "obstacle",
          label: "Front Obstacle",
          status: "active",
          value: "0.8m",
          lastReading: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
        },
        {
          id: "s12",
          type: "gps",
          label: "GPS Module",
          status: "active",
          value: "9 satellites",
          lastReading: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
        },
        {
          id: "s13",
          type: "motion",
          label: "Motion Detector",
          status: "active",
          value: "Walking",
          lastReading: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
        },
        {
          id: "s14",
          type: "gyroscope",
          label: "Gyroscope",
          status: "active",
          value: "Unstable",
          lastReading: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
        },
        {
          id: "s15",
          type: "ultrasonic",
          label: "Ultrasonic Array",
          status: "inactive",
          value: "N/A",
          lastReading: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
        },
      ],
    },
    metrics: {
      totalDistanceToday: 5.8,
      totalDistanceWeek: 32.1,
      obstaclesDetected: 18,
      tripDuration: 90,
      tripFrequency: 2,
      safetyScore: 82,
      incidents: 1,
    },
    lastUpdated: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
    geofenceZones: [
        {
          id: "zone-5",
          name: "Home",
          type: "home",
          center: { lat: -1.97, lng: 30.0528 },
          radius: 200,
          color: "#22c55e",
          enabled: true,
        },
        {
          id: "zone-6",
          name: "Work",
          type: "work",
          center: { lat: -1.958, lng: 30.088 },
          radius: 300,
          color: "#3b82f6",
          enabled: true,
        },
      ],
    status: "moving",
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "alert-1",
    userId: "user-1",
    userName: "Jean Pierre Habimana",
    type: "obstacle_detected",
    severity: "warning",
    message: "Large obstacle detected at 1.2m ahead on KG 7 Ave.",
    location: {
      coordinates: { lat: -1.9441, lng: 30.0619 },
      address: "KG 7 Ave, Kacyiru, Kigali, Rwanda",
      timestamp: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
    },
    timestamp: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
    acknowledged: false,
  },
  {
    id: "alert-2",
    userId: "user-3",
    userName: "Bizimana Emmanuel",
    type: "fall_detected",
    severity: "critical",
    message: "Possible fall detected near KG 220 St. Immediate attention required!",
    location: {
      coordinates: { lat: -1.958, lng: 30.088 },
      address: "KG 220 St, Remera, Kigali, Rwanda",
      timestamp: new Date(now.getTime() - 15 * 60 * 1000).toISOString(),
    },
    timestamp: new Date(now.getTime() - 15 * 60 * 1000).toISOString(),
    acknowledged: false,
  },
  {
    id: "alert-3",
    userId: "user-2",
    userName: "Mukamana Alice",
    type: "low_battery",
    severity: "warning",
    message: "Battery level is at 34%. Device may need charging soon.",
    timestamp: new Date(now.getTime() - 60 * 60 * 1000).toISOString(),
    acknowledged: true,
    acknowledgedBy: "Admin",
    acknowledgedAt: new Date(now.getTime() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "alert-4",
    userId: "user-1",
    userName: "Jean Pierre Habimana",
    type: "geofence_breach",
    severity: "critical",
    message: "Jean Pierre has left the designated safe zone on KG 7 Ave.",
    location: {
      coordinates: { lat: -1.9441, lng: 30.0619 },
      address: "KG 7 Ave, Kacyiru, Kigali, Rwanda",
      timestamp: new Date(now.getTime() - 90 * 60 * 1000).toISOString(),
    },
    timestamp: new Date(now.getTime() - 90 * 60 * 1000).toISOString(),
    acknowledged: false,
  },
  {
    id: "alert-5",
    userId: "user-3",
    userName: "Bizimana Emmanuel",
    type: "hole_stair_detected",
    severity: "warning",
    message: "Staircase detected ahead on KG 220 St. Proceed with caution.",
    location: {
      coordinates: { lat: -1.958, lng: 30.088 },
      address: "KG 220 St, Remera, Kigali, Rwanda",
      timestamp: new Date(now.getTime() - 120 * 60 * 1000).toISOString(),
    },
    timestamp: new Date(now.getTime() - 120 * 60 * 1000).toISOString(),
    acknowledged: false,
  },
  {
    id: "alert-6",
    userId: "user-2",
    userName: "Mukamana Alice",
    type: "unusual_movement",
    severity: "info",
    message: "Unusual movement pattern detected. User may be disoriented.",
    location: {
      coordinates: { lat: -1.951, lng: 30.118 },
      address: "KG 15 Ave, Kimironko, Kigali, Rwanda",
      timestamp: new Date(now.getTime() - 180 * 60 * 1000).toISOString(),
    },
    timestamp: new Date(now.getTime() - 180 * 60 * 1000).toISOString(),
    acknowledged: true,
    acknowledgedBy: "Admin",
    acknowledgedAt: new Date(now.getTime() - 150 * 60 * 1000).toISOString(),
  },
  {
    id: "alert-7",
    userId: "user-1",
    userName: "Jean Pierre Habimana",
    type: "device_disconnected",
    severity: "critical",
    message: "Jean Pierre's ENKONI device has been disconnected for 5+ minutes.",
    timestamp: new Date(now.getTime() - 240 * 60 * 1000).toISOString(),
    acknowledged: true,
    acknowledgedBy: "Admin",
    acknowledgedAt: new Date(now.getTime() - 200 * 60 * 1000).toISOString(),
  },
]
